### ISSUE TITLE
Permission to publish npm update.

### ISSUE THREAD

**Issue by pratikpparikh** [Ritzlgrmft/ionic-configuration-service#5]
Hi Markus,

    Can you please provide me permission to update npm for this module.  My npm and github username is pratikpparikh.  Or allow me to contribute to your project.  I have essentially rewritten all part of the service based on the core foundation that you had laid out to support url configuration aggregation from parent configuration fetch.  Please let me know that your thoughts are do you want me to merge or create my own module?  All my changes are backwards compatible, but if you think this will break your other project then I can easily rename the module and as most of the code is rewritten after the fork.  Please check out the code updates in my fork and tell me what your preference is.  I can work accordingly.  

Regards,
Pratik Parikh

**Comment by Ritzlgrmft** [comment]
Hi Pratik,

Could you please be so kind to explain a little bit more in detail, what the purpose of your change is?
I am not 100% sure if I understand it right.

Thanks
Markus


PS: In general I would prefer to integrate your change in the existing component. This were much better than to have several similar components published.
