### ISSUE TITLE
"Http" will be deprecated

### ISSUE THREAD

**Issue by rrmanzano** [Ritzlgrmft/ionic-configuration-service#6]
Hi Markus,

Just a suggestion, you should consider changing the "Http" dependency to "HttpClient" for any of your upcoming releases, apparently "Http" will be deprecated. You can see the [commit message](https://github.com/angular/angular/commit/37797e2) and the [official docs](https://angular.io/guide/http).

Regards,
Ricardo Ruvalcaba

**Comment by Ritzlgrmft** [comment]
Hi Ricardo,

Thanks for the hint!

If I understand it right `HttpClient` is available from Angular `4.3`. Unfortunately, the currently official supported version by Ionic is `4.1.3`. Therefore this has to wait some days...
